### ISSUE TITLE
Status of project

### ISSUE THREAD

**Issue by krmarien** [alvaro-octal/ngx-tour-ng-bootstrap#1]
Hi,

What is the status of this project? I see this is a "fork" of https://github.com/isaacplmann/ngx-tour
Is there a plan to merge this one back to the original source?

Because this repo is already having backdrop support, I wanted to use this one (but also fix some small issues). To do that I will create a pull request.

However I see that the version in the package.json is not matching the latest version on npmjs. Also it looks from the "Actions" tab that the library was never released from this repo.

Thank you

**Comment by alvaro-octal** [comment]
Hi,

Yes this is a fork of the https://github.com/isaacplmann/ngx-tour, but splited into submodules in order to use GH Actions easily, but I've never finished the publishing from the repo, which I think is the main problem of the original repo, no one has the ability to merge de PRs with the fixes or publish the packages.

Of course any help on maintaining the lib is welcome, and I would try to fix the automatic release so maintainer could publish.

**Comment by alvaro-octal** [comment]
BTW, there is a bit of work on documentation, testing, etc., but last week I updated the lib to _work_ with Angular 11
